name: Cross Compile Rust to arm64

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y

    - name: Set up Rust
      uses: rust-build/rust-build.action@v1.4.5
      with:
        rust-version: stable

    - name: Add arm64 target
      run: rustup target add aarch64-unknown-linux-gnu

    - name: Build for arm64
      run: cargo build --target aarch64-unknown-linux-gnu --release

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: arm64-executable
        path: target/aarch64-unknown-linux-gnu/release/spotifyd
