name: Cross Compile Rust to arm64

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y
        sudo apt-get install -y libasound2-dev portaudio19-dev build-essential libpulse-dev libdbus-1-dev

    - name: Set up Rust
      uses: houseabsolute/actions-rust-cross@v0
      with:
        target: arm-unknown-linux-gnueabihf
        args: "--locked --release"
        strip: true

    - name: Add arm64 target
      run: rustup target add aarch64-unknown-linux-gnu

    - name: Build for arm64
      run: cargo build --target aarch64-unknown-linux-gnu --release

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: arm64-executable
        path: target/aarch64-unknown-linux-gnu/release/spotifyd
